# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lagged_variance_c <- function(X, k, n) {
    .Call(`_partialAR_lagged_variance_c`, X, k, n)
}

estimate_rho_par_c <- function(X) {
    .Call(`_partialAR_estimate_rho_par_c`, X)
}

estimate_par_c <- function(X, rho_max = 1.0) {
    .Call(`_partialAR_estimate_par_c`, X, rho_max)
}

pvmr_par_c <- function(rho, sigma_M, sigma_R) {
    .Call(`_partialAR_pvmr_par_c`, rho, sigma_M, sigma_R)
}

kalman_gain_par_mr <- function(rho, sigma_M, sigma_R) {
    .Call(`_partialAR_kalman_gain_par_mr`, rho, sigma_M, sigma_R)
}

loglik_par_c <- function(Y, rho, sigma_M, sigma_R, M0, R0) {
    .Call(`_partialAR_loglik_par_c`, Y, rho, sigma_M, sigma_R, M0, R0)
}

loglik_par_t_c <- function(Y, rho, sigma_M, sigma_R, M0, R0, nu = 5.0) {
    .Call(`_partialAR_loglik_par_t_c`, Y, rho, sigma_M, sigma_R, M0, R0, nu)
}

